create table modes_paiement (
  mode_paiement_id bigint not null,
  mode_paiement text,
  nombre smallint
);

alter table modes_paiement alter column mode_paiement_id add generated by default as identity (
  sequence name modes_paiement_mode_paiement_id_seq
  start with 1
  increment by 1
  no minvalue
  no maxvalue
  cache 1
);
