alter table "public"."distributions" drop constraint "distributions_depot_id_fkey";

alter table "public"."distributions" drop constraint "distributions_jardin_id_fkey";

alter table "public"."distributions" drop constraint "distributions_tournee_id_fkey";

alter table "public"."tournees" alter column "preparation_id" set not null;

alter table "public"."tournees" alter column "tournee_id" add generated by default as identity;

alter table "public"."adherents" add constraint "adherents_depot_id_fkey" FOREIGN KEY (depot_id) REFERENCES depots(depot_id) not valid;

alter table "public"."adherents" validate constraint "adherents_depot_id_fkey";

alter table "public"."adresses" add constraint "adresses_jardin_id_fkey" FOREIGN KEY (jardin_id) REFERENCES jardins(jardin_id) not valid;

alter table "public"."adresses" validate constraint "adresses_jardin_id_fkey";

alter table "public"."contacts" add constraint "contacts_jardin_id_fkey" FOREIGN KEY (jardin_id) REFERENCES jardins(jardin_id) not valid;

alter table "public"."contacts" validate constraint "contacts_jardin_id_fkey";

alter table "public"."fermetures" add constraint "fermetures_saison_id_fkey" FOREIGN KEY (saison_id) REFERENCES saisons(saison_id) not valid;

alter table "public"."fermetures" validate constraint "fermetures_saison_id_fkey";

alter table "public"."frequences" add constraint "frequences_jardin_id_fkey" FOREIGN KEY (jardin_id) REFERENCES jardins(jardin_id) not valid;

alter table "public"."frequences" validate constraint "frequences_jardin_id_fkey";

alter table "public"."tournees" add constraint "tournees_calendrier_id_fkey" FOREIGN KEY (calendrier_id) REFERENCES calendriers(calendrier_id) not valid;

alter table "public"."tournees" validate constraint "tournees_calendrier_id_fkey";

alter table "public"."distributions" add constraint "distributions_depot_id_fkey" FOREIGN KEY (depot_id) REFERENCES depots(depot_id) not valid;

alter table "public"."distributions" validate constraint "distributions_depot_id_fkey";

alter table "public"."distributions" add constraint "distributions_jardin_id_fkey" FOREIGN KEY (jardin_id) REFERENCES jardins(jardin_id) ON UPDATE CASCADE not valid;

alter table "public"."distributions" validate constraint "distributions_jardin_id_fkey";

alter table "public"."distributions" add constraint "distributions_tournee_id_fkey" FOREIGN KEY (tournee_id) REFERENCES tournees(tournee_id) not valid;

alter table "public"."distributions" validate constraint "distributions_tournee_id_fkey";
