create table preparations (
  preparation_id bigint not null,
  jardin_id bigint not null,
  preparation text not null,
  jour smallint not null
);

alter table preparations 
  alter column preparation_id 
  add generated by default as identity;

alter table only preparations
  add primary key (preparation_id);

create table calendriers (
  calendrier_id bigint not null,
  jardin_id bigint not null,
  calendrier text not null
);

alter table calendriers 
  alter column calendrier_id 
  add generated by default as identity;

alter table calendriers
  add foreign key (jardin_id) references jardins on delete cascade not valid;

alter table calendriers
  validate constraint calendriers_jardin_id_fkey;

alter table only calendriers
  add primary key (calendrier_id);

create table tournees (
  tournee_id bigint not null,
  jardin_id bigint not null,
  tournee text,
  preparation_id bigint not null,
  calendrier_id bigint,
  ordre smallint,
  couleur text
);

alter table only tournees
  add foreign key (jardin_id) references jardins;

alter table only tournees
  add foreign key (preparation_id) references preparations;

alter table only tournees
  add primary key (tournee_id);

alter table tournees
  add foreign key (calendrier_id) references calendriers not valid;

alter table tournees
  validate constraint tournees_calendrier_id_fkey;

alter table tournees alter column tournee_id add generated by default as identity;

create table distributions (
  distribution_id bigint not null,
  jardin_id bigint not null,
  tournee_id bigint not null,
  depot_id bigint,
  adherent_id bigint,
  ordre smallint
);

alter table distributions
  alter column distribution_id 
  add generated by default as identity;

alter table only distributions
  add primary key (distribution_id);

alter table distributions
  add foreign key (depot_id) references depots not valid;

alter table distributions
  add foreign key (adherent_id) references adherents not valid;

alter table distributions
  validate constraint distributions_depot_id_fkey;

alter table distributions
  add foreign key (jardin_id) references jardins on update cascade not valid;

alter table distributions
  validate constraint distributions_jardin_id_fkey;

alter table distributions
  add foreign key (tournee_id) references tournees not valid;

alter table distributions
  validate constraint distributions_tournee_id_fkey;
