create table modes_paiement (
  mode_paiement_id bigint not null,
  mode_paiement text,
  nombre smallint
);

alter table modes_paiement 
  alter column mode_paiement_id 
  add generated by default as identity;
