create table plannings (
  planning_id bigint not null,
  calendrier_id bigint,
  jour date
);

alter table plannings 
  alter column planning_id 
  add generated by default as identity;

alter table only plannings
  add constraint plannings_calendrier_id_fkey
  foreign key (calendrier_id) references calendriers(calendrier_id);

alter table only plannings
  add constraint plannings_pkey
  primary key (planning_id);


