create table abonnements (
	abonnement_id int8 not null,
	created_at timestamptz not null default now(),
	adherent_id int8 null,
	panier_id int8 null,
	date_debut date null,
	nombre int2 null,
	montant numeric null,
	mode_paiement_id int8 null,
	saison_id int8 null
);

alter table abonnements alter column abonnement_id add generated by default as identity (
  sequence name abonnements_abonnement_id_seq
  start with 1
  increment by 1
  no minvalue
  no maxvalue
  cache 1
);

alter table abonnements
  add constraint abonnements_pkey
  primary key (abonnement_id);

alter table abonnements
  add constraint abonnements_adherent_id_fkey
  foreign key (adherent_id) references adherents(adherent_id) on delete cascade not valid;

alter table abonnements
  add constraint abonnements_panier_id_fkey
  foreign key (panier_id) references paniers(panier_id);
