
create table produits (
    produit_id bigint not null,
    jardin_id bigint not null,
    produit text not null,
    prix numeric,
    marge numeric
);

alter table produits 
  alter column produit_id 
  add generated by default as identity;

alter table only produits
  add primary key (produit_id);

alter table only produits
  add foreign key (jardin_id) references jardins(jardin_id);

alter table produits enable row level security;

create policy "Lecture publique"
on produits
as permissive
for select
to public
using (true);


-- paniers

create table paniers (
  panier_id bigint not null,
  produit_id bigint not null,
  panier text not null,
  frequence_id bigint,
  quantite smallint,
  prix numeric
);

alter table paniers 
  alter column panier_id 
  add generated by default as identity;

alter table only paniers
  add primary key (panier_id);

alter table only paniers
  add foreign key (produit_id) references produits;

alter table paniers
  add foreign key (frequence_id) references frequences not valid;

alter table paniers
  validate constraint paniers_frequence_id_fkey;

alter table paniers enable row level security;

create policy "Lecture publique"
on paniers
as permissive
for select
to public
using (true);

create table propositions (
  proposition_id bigint not null,
  frequence_id bigint not null,
  planning_id bigint not null
);

alter table propositions 
  alter column proposition_id 
  add generated by default as identity;