create table depots (
  depot_id bigint not null,
  jardin_id bigint not null,
  depot text not null,
  adresse_id bigint,
  contact_id bigint,
  capacite integer default 0
);

alter table depots 
  alter column depot_id 
  add generated by default as identity;

alter table only depots
  add primary key (depot_id);

alter table only depots
  add foreign key (jardin_id) references jardins on delete cascade;

alter table depots
  add foreign key (adresse_id) references adresses not valid;

alter table depots validate constraint depots_adresse_id_fkey;

alter table depots
  add foreign key (contact_id) references contacts not valid;

alter table depots validate constraint depots_contact_id_fkey;

alter table depots enable row level security;

create policy "Lecture publique"
on depots
as permissive
for select
to public
using (true);
