create type livraison as enum (
  'à livrer',
  'livré',
  'non pris',
  'perdu'
);

create table livraisons (
  livraison_id bigint not null,
  jardin_id bigint not null,
  abonnement_id bigint not null,
  distribution_id bigint not null,
  qte numeric  not null default '1'::numeric,
  livre livraison not null default  'à livrer',
  jour date null
);

alter table livraisons alter column livraison_id add generated by default as identity (
  sequence name livraisons_livraison_id_seq
  start with 1
  increment by 1
  no minvalue
  no maxvalue
  cache 1
);

alter table livraisons
  add constraint livraison_pkey primary key (livraison_id);


alter table livraisons
  add constraint livraisons_jardin_id_fkey
  foreign key (jardin_id) references jardins (jardin_id) on delete cascade not valid;

alter table livraisons
  validate constraint livraisons_jardin_id_fkey;

alter table livraisons
  add constraint livraisons_abonnement_id_fkey
  foreign key (abonnement_id) references abonnements(abonnement_id) on delete cascade not valid;

alter table livraisons
  validate constraint livraisons_abonnement_id_fkey;

alter table livraisons
  add constraint livraisons_distribution_id_fkey
  foreign key (distribution_id) references distributions(distribution_id) not valid;

alter table livraisons
  validate constraint livraisons_distribution_id_fkey;


create view check_livraisons_feries as
  select l.jour
   from (livraisons l
     join feries f on ((f.jour = l.jour)));

alter table livraisons enable row level security;

create policy "Lecture publique"
on livraisons
as permissive
for select
to public
using (true);
