-- show search_path;
-- set search_path to "\$user", public, extensions;
-- create schema extensions

create table jardins (
  jardin_id bigint not null,
  jardin text,
  adresse_id bigint,
  tva text,
  contact_id bigint
);

alter table jardins 
  alter column jardin_id 
  add generated by default as identity;

alter table only jardins
  add primary key (jardin_id);

alter table jardins enable row level security;

create policy "Lecture publique"
  on jardins
  as permissive
  for select
  to public
  using (true);

-- adresses

create extension postgis schema extensions;

create table adresses (
  adresse_id bigint not null,
  jardin_id bigint,
  adresse text,
  codepostal text,
  ville text,
  localisation geometry(point, 4326) default null::geometry
);

alter table adresses 
  alter column adresse_id 
  add generated by default as identity;

create index adresses_localisation_idx
  on adresses
  using gist (localisation);

alter table only adresses
  add primary key (adresse_id);

alter table adresses
  add foreign key (jardin_id) references jardins not valid;

alter table adresses
  validate constraint adresses_jardin_id_fkey;

alter table jardins
  add foreign key (adresse_id) references adresses on delete set null not valid;

alter table jardins
  validate constraint jardins_adresse_id_fkey;


alter table adresses enable row level security;

create policy "Lecture publique"
on adresses
as permissive
for select
to public
using (true);


-- contacts

create table contacts (
  contact_id bigint not null,
  jardin_id bigint,
  contact text,
  telephone text,
  email text
);

alter table contacts 
  alter column contact_id 
  add generated by default as identity;

alter table only contacts
  add primary key (contact_id);

alter table contacts
  add foreign key (jardin_id) references jardins not valid;

alter table contacts
  validate constraint contacts_jardin_id_fkey;

alter table jardins
  add foreign key (contact_id) references contacts(contact_id) on delete set null not valid;

alter table jardins
  validate constraint jardins_contact_id_fkey;

alter table contacts enable row level security;

create policy "Lecture publique"
on contacts
as permissive
for select
to public
using (true);
