create table plannings (
  planning_id bigint not null,
  calendrier_id bigint,
  jour date
);

alter table plannings 
  alter column planning_id 
  add generated by default as identity;

alter table only plannings
  add foreign key (calendrier_id) references calendriers;

alter table only plannings
  add primary key (planning_id);


