create table adherents (
  adherent_id bigint not null,
  created_at timestamp with time zone default now() not null,
  jardin_id bigint not null,
  adherent text not null,
  depot_id bigint,
  email text,
  date_sortie date
);

alter table adherents alter column adherent_id add generated by default as identity (
  sequence name adherent_id_seq
  start with 1
  increment by 1
  no minvalue
  no maxvalue
  cache 1
);

alter table only adherents
  add constraint adherents_pkey primary key (adherent_id);

alter table only adherents
  add constraint adherents_jardin_id_fkey foreign key (jardin_id) references jardins(jardin_id);


create table adhesions (
  adhesion_id bigint not null,
  created_at timestamp with time zone default now() not null,
  adherent_id bigint,
  jardin_id bigint,
  date_adhesion date,
  montant numeric
);

alter table adhesions alter column adhesion_id add generated by default as identity (
  sequence name adhesion_id_seq
  start with 1
  increment by 1
  no minvalue
  no maxvalue
  cache 1
);

alter table only adhesions
  add constraint adhesions_pkey primary key (adhesion_id);

alter table only adhesions
  add constraint adhesions_adherent_id_fkey foreign key (adherent_id) references adherents(adherent_id);

alter table only adhesions
  add constraint adhesions_jardin_id_fkey foreign key (jardin_id) references jardins(jardin_id);
