create type livraison as enum (
  'à livrer',
  'livré',
  'non pris',
  'perdu'
);

create table livraisons (
  livraison_id bigint not null,
  jardin_id bigint not null,
  abonnement_id bigint not null,
  distribution_id bigint not null,
  qte numeric  not null default '1'::numeric,
  livre livraison not null default  'à livrer',
  semaine smallint null,
  saison_id bigint null
);

alter table livraisons alter column livraison_id add generated by default as identity (
  sequence name livraisons_livraison_id_seq
  start with 1
  increment by 1
  no minvalue
  no maxvalue
  cache 1
);

alter table livraisons
  add constraint livraison_pkey primary key (livraison_id);

alter table livraisons
  add constraint livraison_jardin_id_fkey
  foreign key (jardin_id) references jardins (jardin_id) on delete cascade;
