
create table produits (
    produit_id bigint not null,
    jardin_id bigint not null,
    produit text not null
);

alter table produits alter column produit_id add generated by default as identity (
    sequence name produit_id_seq
    start with 1
    increment by 1
    no minvalue
    no maxvalue
    cache 1
);

alter table only produits
  add constraint produits_pkey
  primary key (produit_id);

alter table only produits
  add constraint produits_jardin_id_fkey
  foreign key (jardin_id) references jardins(jardin_id);


alter table produits enable row level security;

create policy "Lecture publique"
on produits
as permissive
for select
to public
using (true);


-- paniers

create table paniers (
    panier_id bigint not null,
    produit_id bigint not null,
    panier text not null,
    frequence_id bigint,
    quantite smallint,
    prix numeric
);

alter table paniers alter column panier_id add generated by default as identity (
    sequence name panier_id_seq
    start with 1
    increment by 1
    no minvalue
    no maxvalue
    cache 1
);

alter table only paniers
  add constraint paniers_pkey
  primary key (panier_id);

alter table only paniers
  add constraint paniers_produit_id_fkey
  foreign key (produit_id) references produits(produit_id);

alter table paniers
  add constraint paniers_frequence_id_fkey
  foreign key (frequence_id) references frequences(frequence_id) not valid;

alter table paniers
  validate constraint paniers_frequence_id_fkey;

alter table paniers enable row level security;

create policy "Lecture publique"
on paniers
as permissive
for select
to public
using (true);
