create table fournisseurs (
  fournisseur_id bigint not null,
  jardin_id bigint not null,
  fournisseur text,
  tva text,
  adresse_id bigint
);

alter table fournisseurs alter column fournisseur_id add generated by default as identity (
  sequence name fournisseur_id_seq
  start with 1
  increment by 1
  no minvalue
  no maxvalue
  cache 1
);

alter table only fournisseurs
  add constraint fournisseurs_pkey
  primary key (fournisseur_id);

alter table only fournisseurs
  add constraint fournisseurs_jardin_id_fkey
  foreign key (jardin_id) references jardins(jardin_id) on delete cascade;

alter table fournisseurs
  add constraint fournisseurs_adresse_id_fkey
  foreign key (adresse_id) references adresses(adresse_id) on delete set null not valid;

alter table fournisseurs
  validate constraint fournisseurs_adresse_id_fkey;


alter table fournisseurs enable row level security;

create policy "Lecture publique"
on fournisseurs
as permissive
for select
to public
using (true);
