### Tous les jardins
GET https://qjnieztpwnwroinqrolm.supabase.co/rest/v1/jardins?select=jardin_id,jardin,tva,adresses!jardins_adresse_id_fkey(adresse,ville),contacts!jardins_contact_id_fkey(contact,telephone)
apikey: {{$dotenv APIKEY}}

### Tous les dépôts
GET https://qjnieztpwnwroinqrolm.supabase.co/rest/v1/depots?jardin_id=eq.1&select=depot_id,depot,capacite,adresses(adresse,ville),contacts(contact,telephone)
apikey: {{$dotenv APIKEY}}

### Tous les adhérents
GET https://qjnieztpwnwroinqrolm.supabase.co/rest/v1/adherents?jardin_id=eq.1&select=adherent,email,date_sortie,adhesions(adhesion_id)
apikey: {{$dotenv APIKEY}}

### Toutes les préparations
GET https://qjnieztpwnwroinqrolm.supabase.co/rest/v1/preparations?jardin_id=eq.1&select=preparation_id,preparation,jour,tournees(tournee_id, tournee, ordre, distributions(depots(depot, adresses(adresse, ville, localisation))))
apikey: {{$dotenv APIKEY}}