

### N'existe plus
GET https://qjnieztpwnwroinqrolm.supabase.co/rest/v1/preparer?select=*
apikey: {{$dotenv APIKEY}}


###
POST https://qjnieztpwnwroinqrolm.supabase.co/rest/v1/rpc/preparer
apikey: {{$dotenv APIKEY}}
content-type: application/json

{ "_semaine": "11" }
